### ISSUE TITLE
error starting chao enabled profile

### ISSUE THREAD

**Issue by dbyrne28** [codecentric/chaos-monkey-spring-boot#176] opened 2020-04-17 19:37 UTC
I seem to have an issue similar to #118 but it is not fixed using release 2.2.0 or 2.3.0-SHAPSHOT. org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'chaos.monkey-de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyProperties': Could not bind properties to 'ChaosMonkeyProperties' : prefix=chaos.monkey, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'chaosMonkeyRequestScope': Requested bean is currently in creation: Is there an unresolvable circular reference? com.ibm.ws.webcontainer.osgi.DynamicVirtualHost startWebApp

**Comment by dbyrne28** [comment] 2020-04-17 19:41
Spring versions:
spring-aop-5.0.6.RELEASE.jar
spring-aspects-5.0.6.RELEASE.jar
spring-beans-5.0.6.RELEASE.jar
spring-boot-2.0.2.RELEASE.jar
spring-boot-actuator-2.0.2.RELEASE.jar
spring-boot-actuator-autoconfigure-2.0.2.RELEASE.jar
spring-boot-autoconfigure-2.0.2.RELEASE.jar
spring-boot-configuration-processor-2.0.2.RELEASE.jar
spring-boot-starter-2.0.2.RELEASE.jar
spring-boot-starter-actuator-2.0.2.RELEASE.jar
spring-boot-starter-aop-2.0.2.RELEASE.jar
spring-boot-starter-data-jpa-2.0.2.RELEASE.jar
spring-boot-starter-jdbc-2.0.2.RELEASE.jar
spring-boot-starter-json-2.0.2.RELEASE.jar
spring-boot-starter-logging-2.0.2.RELEASE.jar
spring-boot-starter-mail-2.0.2.RELEASE.jar
spring-boot-starter-web-2.0.2.RELEASE.jar
spring-cloud-commons-2.0.1.RELEASE.jar
spring-cloud-consul-config-2.0.1.RELEASE.jar
spring-cloud-consul-core-2.0.1.RELEASE.jar
spring-cloud-consul-discovery-2.0.0.RELEASE.jar
spring-cloud-context-2.0.1.RELEASE.jar
spring-cloud-starter-consul-2.0.1.RELEASE.jar
spring-cloud-starter-consul-config-2.0.1.RELEASE.jar
spring-context-5.0.6.RELEASE.jar
spring-context-support-5.0.6.RELEASE.jar
spring-core-5.0.6.RELEASE.jar
spring-data-commons-2.0.7.RELEASE.jar
spring-data-jpa-2.0.7.RELEASE.jar
spring-expression-5.0.6.RELEASE.jar
spring-instrument-5.0.6.RELEASE.jar
spring-jcl-5.0.6.RELEASE.jar
spring-jdbc-5.0.6.RELEASE.jar
spring-jms-5.0.6.RELEASE.jar
spring-messaging-5.0.6.RELEASE.jar
spring-orm-5.0.6.RELEASE.jar
spring-plugin-core-1.2.0.RELEASE.jar
spring-plugin-metadata-1.2.0.RELEASE.jar
spring-retry-1.2.2.RELEASE.jar
spring-security-crypto-5.0.5.RELEASE.jar
spring-test-5.0.6.RELEASE.jar
spring-tx-5.0.6.RELEASE.jar
spring-web-5.0.6.RELEASE.jar
spring-webmvc-5.0.6.RELEASE.jar
springfox-core-2.6.1.jar
springfox-schema-2.6.1.jar
springfox-spi-2.6.1.jar
springfox-spring-web-2.6.1.jar
springfox-swagger2-2.6.1.jar
springfox-swagger-common-2.6.1.jar
swagger-annotations-1.5.10.jar
swagger-models-1.5.10.jar

**Comment by maiksensi** [comment] 2020-04-17 21:10
Hey @dbyrne28,
thanks for submitting this issue and the versions you used. For us it is very hard (if not impossible) to reproduce and debug this without a minimal reproducable example. If you can supply one, that would definitely help, because otherwise I don't see us tracking this down anytime soon.

**Comment by dbyrne28** [comment] 2020-04-18 15:35
Thank you for your consideration. Our app is complex and the time needed to track this down would be great. We have discovered that rolling back to version 2.0.0 fixed the issue if that helps.

**Comment by maiksensi** [comment] 2020-04-19 09:14
Rolling back to 2.0.x may be a valid approach for you, depending on what features you need. Make  sure to check whether your spring boot version is supported: https://codecentric.github.io/chaos-monkey-spring-boot/#support. 
However, in order to help you, we need you to help us. That said, if the bug is similar to the one you linked, a sample project (using the spring boot initializr) with your spring cloud dependencies and a sample controller should not be too much work to get this to a reproducible state.

**Comment by maiksensi** [comment] 2020-05-26 08:04
closing this for now, feel free to reopen it once more information can be provided.

**Closed by maiksensi** 2020-05-26 08:04 UTC
Labels: waiting-for-feedback
