### ISSUE TITLE
Serialization problem when request "chaosmonkey" Endpoint

### ISSUE THREAD

**Issue by bensonarce** [codecentric/chaos-monkey-spring-boot#75] opened 2019-06-21 16:22 UTC
Spring boot version: 2.1.3.RELEASE
Chaos Monkey: 2.0.1

Getting this error when request
GET --> http://localhost:7001/chaos/actuator/chaosmonkey

`{
    "code": "500",
    "message": "Type definition error: [simple type, class org.springframework.aop.framework.DefaultAdvisorChainFactory]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.aop.framework.DefaultAdvisorChainFactory and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeySettings[\"assaultProperties\"]->de.codecentric.spring.boot.chaos.monkey.configuration.AssaultProperties$$EnhancerBySpringCGLIB$$b9e4d763[\"CGLIB$CALLBACK_0\"]->org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor[\"advised\"]->org.springframework.aop.framework.ProxyFactory[\"advisorChainFactory\"])"
}`

**Comment by bensonarce** [comment] 2019-06-21 19:14
i tried with Chaos monkey 2.0.2 and Spring boot 2.1.3-RELEASE and now, i cannot start the app

`SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyConfiguration': Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chaos.monkey.assaults-de.codecentric.spring.boot.chaos.monkey.configuration.AssaultProperties': Initialization of bean failed; nested exception is java.lang.AbstractMethodError
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]`

**Comment by maiksensi** [comment] 2019-08-12 20:53
Hey @bensonarce thanks for submitting this. Can you please provide us with a minimal working example? I tried to reproduce it, but couldnt.

**Comment by maiksensi** [comment] 2019-08-19 21:34
Closing this for now as we cannot reproduce the issue. We would be happy to help with some more information. Especially a minimal working example would help us a great deal. Please feel free to repopen this issue.

**Closed by maiksensi** 2019-08-19 21:34 UTC
Labels: hold, waiting-for-feedback
