### ISSUE TITLE
Inconsistent pattern for values of Level field

### ISSUE THREAD

**Issue by priyadarshni1828** [codecentric/chaos-monkey-spring-boot#178] opened 2020-05-06 12:23 UTC
I am using below assault configuration to inject latency assault in my spring boot application which is deployed on PCF.
"assaults_configuration": {
                        "level": 2,
                        "latencyRangeStart": 10000,
                        "latencyRangeEnd": 10000,
                        "latencyActive": true,
                        "exceptionsActive": false,
                        "killApplicationActive": false,
			"watchedCustomServices": ["com.example.demoChaos.EmployeeController.getEmployees"]
                    }
The level field in above code should state the frequency by which assault should be injected in the application requests. For values more than 1, it is giving inconsistent pattern.
For example: For value 2, it should add the latency to each alternate request made to the server, but it is not so. It adds the latency to random number of requests.
Could anyone help me figure out this?

**Comment by fletchgqc** [comment] 2020-05-08 05:07
Duplicate of #172. Please see explanation there.

**Closed by fletchgqc** 2020-05-08 05:07 UTC
