### ISSUE TITLE
In your configuration,my application must have "TaskScheduler" bean, otherwise  timed tasks will not take effect.Why you don't give

### ISSUE THREAD

**Issue by zuoqi1993125** [codecentric/chaos-monkey-spring-boot#73] opened 2019-06-05 11:54 UTC
@Bean
    public ChaosMonkeyScheduler scheduler(@Nullable TaskScheduler scheduler, ChaosMonkeyRuntimeScope runtimeScope) {
        ScheduledTaskRegistrar registrar = null;
        if (scheduler != null) {
            registrar = new ScheduledTaskRegistrar();
            registrar.setTaskScheduler(scheduler);
        }
        return new ChaosMonkeyScheduler(registrar, assaultProperties, runtimeScope);
    }

**Comment by maiksensi** [comment] 2019-08-09 11:37
Hey @zuoqi1993125 thanks for submitting this issue. I am trying to understand what the problem is. Can you describe it a bit more in details and maybe provide us with a minimal example to reproduce your bug?

**Comment by maiksensi** [comment] 2019-08-15 20:32
Closing this for now. If you are able to supply us with some more information, feel free to re-open this.

**Closed by maiksensi** 2019-08-15 20:32 UTC
Labels: hold, waiting-for-feedback
