### ISSUE TITLE
Assault level behaves not as described

### ISSUE THREAD

**Issue by rusyasoft** [codecentric/chaos-monkey-spring-boot#172] opened 2020-03-23 23:26 UTC
Assault level description in the documentation says:
"How many requests are to be attacked. 1 each request, 5 each 5th request is attacked"

When I have tested, it is not behaving as it has been described. Maybe it behaves in a probabilistic manner, not sure. For example, when I set level: 2, it means it should be an attack, not-attack, attack, not-attack, ... and so on. But it behaves almost randomly, sometimes attack, attack, not-attack, attack, not-attack, not-attack, not-attack, not-attack, ...

So is this normal? If it is normal then what should I do to get more deterministic behavior?

I'm using version 2.1.1 -> 'de.codecentric:chaos-monkey-spring-boot:2.1.1'

Thank You in Advance

**Comment by fletchgqc** [comment] 2020-03-24 08:19
Hi @rusyasoft . The behaviour you describe is by design. We feel that it is more realistic when a service behaves like this, than exactly every second request being attacked.

Two questions:
a) Do you have a need for it to behave in a deterministic manner? If so, feel free to try to convince us that this should be implemented as an option.

b) Where did you read that in the documentation? We should adjust the documentation to make the desired behaviour clear.

**Comment by rusyasoft** [comment] 2020-03-24 16:22
Hi @fletchgqc 
Thanks for developing and supporting this project.

a) I understand that Chaos Engineering somehow requires us to make it look like a "real environment" which is more close to the probabilistic approach. But it could be good to have a determinism switch for the people who need it. With determinism switch, wider usage becomes possible, such as specifically planned test cases, where we expect it throws exception at 6th trial, so how would our client behave. But that way it may become little outside of Chaos Engineering scope. 

b) [here](https://codecentric.github.io/chaos-monkey-spring-boot/2.2.0/)   check the table 4.1 or just search for text "How many requests are to be attacked. 1 each request, 5 each 5th request is attacked"

Thanks again

**Comment by maiksensi** [comment] 2020-04-06 14:42
The docs need a restructuring. That being said, I think we should add a short info that this is the intended behavior. I basically feel that there is need for both cases. @rusyasoft if you want to implement something that works in a more "predictable" way, feel free to discuss some details here with us and then add a PR. We are happy to help and contributions are always welcome.

**Comment by maiksensi** [comment] 2020-06-10 08:50
Closing this. Feel free to reopen it if needed. If we need a docs update we can create a new issue.

**Closed by maiksensi** 2020-06-10 08:50 UTC
Labels: enhancement, good first issue, waiting-for-feedback
