### ISSUE TITLE
@Repository watcher did not work

### ISSUE THREAD

**Issue by MrBW** [codecentric/chaos-monkey-spring-boot#36] opened 2018-07-27 07:39 UTC
Repository Watcher is not invoked 
Example can be found in branch metrics
https://github.com/codecentric/chaos-monkey-spring-boot/tree/2.0.1-metrics

**Comment by singhgarima** [comment] 2018-09-20 23:42
@MrBW when is the release of 2.0.1 planned? This bug is currently impacting us and we would like to use your new 2.0.1 version.

Also is this issue a duplicate of https://github.com/codecentric/chaos-monkey-spring-boot/issues/26? Can you close of them in favor of the other?

**Closed** 2018-09-30 10:38 UTC
Labels: bug
