### ISSUE TITLE
Startup Issues when no RestController is present

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#110] opened 2019-09-04 12:26 UTC
If I create an empty spring boot sample project (using [spring initializr](https://start.spring.io/) 2.1.7 with web dependency) and add chaosmonkey as dependency (and add default properties), the application doesnt start.
## Expected Behavior
Application should boot/start up.

## Current Behavior
Application crashes with following exception in [crash.log](https://github.com/codecentric/chaos-monkey-spring-boot/files/3574448/crash.log)

## Steps to Reproduce

1. https://start.spring.io/ - Generate project 
2. Open Project
3. Add chaosmonkey dependency
```
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>chaos-monkey-spring-boot</artifactId>
            <version>2.1.0</version>
        </dependency>
```
4. Insert in application.properties:
```
spring.profiles.active=chaos-monkey
chaos.monkey.enabled=true

chaos.monkey.watcher.controller=false
chaos.monkey.watcher.restController=true
chaos.monkey.watcher.service=true
chaos.monkey.watcher.repository=false
```
5. Start App

## Context (Environment)
Windows 10, Java 12.0.2

**Comment by maiksensi** [comment] 2019-09-04 16:42
@fletchgqc do you know whats going on here? It kinda seems watcher related.

**Comment by maiksensi** [comment] 2019-09-04 16:43
Workaround till this is fixed: 

- Create an empty class annotated with `@RestController`.

**Comment by fletchgqc** [comment] 2019-09-06 15:07
Thanks for the nice steps to reproduce. That helped me to find it.

The problem is in pom.xml: 

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>

CMSB assumes that the application will provide spring web. You can get around the problem by adding

     @ConditionalOnClass(name = "org.springframework.web.bind.annotation.RestController")

to ChaosMonkeyConfiguration where the SpringRestControllerAspect bean is declared. However, then another exception is thrown because of the ChaosMonkeyRestEndpoint (for actuator). @WtfJoke and I agreed offline that it is a fair assumption that a SB application will provide web or webflux and either of those fix the problem. Therefore, let's close this as "won't fix".

**Closed** 2019-09-06 15:13 UTC
Labels: bug, help wanted
